### ISSUE TITLE
[Suggestion] Tidy up about section of repo

### ISSUE THREAD

**Issue by PolyCatDev** [AlterNStuff/alterhomelabs#5]
## Suggestion

GitHub lets you link a website to the project for easy access. I was thinking you could do that. And while you are there you can remove the tings you don't use (eg: Releases and Packages)

## Example
![image](https://github.com/user-attachments/assets/ce40ac84-f93e-4388-8b78-fbab636d31b7)

**Comment by AlterNStuff** [comment]
Done and dusted, thanks for the suggestion
