### ISSUE TITLE
[BUG] UI broken on vertical monitors

### ISSUE THREAD

**Issue by PolyCatDev** [AlterNStuff/alterhomelabs#7]
## Issue
Cards broken on tall displays

## Cause
Use of right and left margin instead of flexbox

## Fix
Make a `section` tag that stores all the cards and use flexbox to align them in the middle and properly space out elements

Basically what I did at PR #3

**Comment by AlterNStuff** [comment]
got it, will fix

**Comment by AlterNStuff** [comment]
fixeth
