### ISSUE TITLE
[ISSUE] Image not in "images" folder

### ISSUE THREAD

**Issue by PolyCatDev** [AlterNStuff/alterhomelabs#8]
## Issue
Image `signal-2024-12-13-155607_002.jpeg` for some reason is not in the images folder

## Fix
Move it there lmao. I'm just bored at this point and making bug reports for what I find. It's 11:30 PM

**Comment by AlterNStuff** [comment]
lmao stop making dumbass bug reports, also the image doesnt work if its not in the same folder (even if i specify the path to it) and i tried it multiple times so i just moved it into the main folder, might fix later if i find out why its not working properly
